export const API_KEYS = {
  GET_SCHOOL_INFO: "GET_SCHOOL_INFO",
  GET_AUCTION: "GET_AUCTION",
  GET_NFT: "GET_NFT",
  BID_NFT: "BID_NFT",
  GET_SCHOOLS: "GET_SCHOOLS",
  GET_OWNED_NFTS: "GET_OWNED_NFTS",
  CREATE_NFT: "CREATE_NFT",
  GET_WALLET: "GET_WALLET",
  ADD_BALANCE: "ADD_BALANCE",
};
